package orm.fox.liteorm.db.greendao.entity;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BUSINESS_REPORT".
 */
@Entity
public class BusinessReport implements Serializable{


    private static final long serialVersionUID = 1L;
    @Id(autoincrement = true)
    private Long id;
    private String employee;
    private String customer;
    private java.util.Date startExpire;
    private java.util.Date endExpire;
    private String city;
    private java.util.Date createTime;
    private String taskId;

    @Generated(hash = 448939079)
    public BusinessReport() {
    }

    public BusinessReport(Long id) {
        this.id = id;
    }

    @Generated(hash = 2072139650)
    public BusinessReport(Long id, String employee, String customer, java.util.Date startExpire, java.util.Date endExpire, String city, java.util.Date createTime, String taskId) {
        this.id = id;
        this.employee = employee;
        this.customer = customer;
        this.startExpire = startExpire;
        this.endExpire = endExpire;
        this.city = city;
        this.createTime = createTime;
        this.taskId = taskId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmployee() {
        return employee;
    }

    public void setEmployee(String employee) {
        this.employee = employee;
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public java.util.Date getStartExpire() {
        return startExpire;
    }

    public void setStartExpire(java.util.Date startExpire) {
        this.startExpire = startExpire;
    }

    public java.util.Date getEndExpire() {
        return endExpire;
    }

    public void setEndExpire(java.util.Date endExpire) {
        this.endExpire = endExpire;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

}
